### PR TITLE
tstp2agda 0.1.1.0

### PR DESCRIPTION
**Pull request by jonaprieto**
This version has some improvements @asr and @agomezl, some of them:
- Support for GHC 7.6.3, 7.8.4, 7.10, y 8.10.
- Configuration file cabal improved.
- The module Args.hs was rewritten, now we have Options.hs with a better handle of options.
- New modules for reorganizing the library TSTP datatypes and Proof datatypes.
- Test folder relocated.
- New module Utils.
- Mostly all things typed.
- Explicit and only necessary Imports.
- Hlint suggestions.

### CODE REVIEW

**Comment by asr** [comment]
@agomezl, are you going to merge this PR?

**Comment by asr** [comment]
@jonaprieto, I suggest to wait @agomezl answer, so please stop adding commits to this PR.

**Comment by jonaprieto** [comment]
@asr Ok.

**Comment by agomezl** [comment]
Well, I am terribly embarrassed for not realizing until just now of the existence of this pull request. I will get right on it and try to provide some feedback.

**Comment by agomezl** [comment]
A couple of comments:

* The style changes and type signatures on `let`/`where` statements are useful, are you following any style guide?
* The support for multiple GHC version is great! and so are the multi-GHC travis tests!
* Moving the small example from `T2A.hs` into `README.md` was a good idea, but that removes it from the haddock documentation, maybe we can duplicate it?
* What was the issue with `stack`? Is there any reason you stopped using it?
* Even though this repo is not a prime example of it, I'm not a big fan of merges and tiny little commits, I understand that your workflow is somehow based on [git-flow](https://datasift.github.io/gitflow/IntroducingGitFlow.html) and that is wonderful but:
  - Why are you adding files when you are thinking about removing them? (615f88b and 1f32b41) 
  - Some commits (721d3fb, b390387, 7f2cc36 ... etc) are very small, and this is fine when you are developing, but once everything is done (it think) is a good idea to squash some of this changes into a/ more meaningful commit/s (with some nice message 1f32b41)
  - There is some inconsistency into what goes to a feature/fix branch (7f2cc36) and what is added directly in the `development` and/or `master` branch (70d2c81, f96c3d0, 31b1c44)
  - I have the impression that at some point the whole idea of the parallel `development` branch was abandoned, and that only contributes to my confusion
  - There are some anonymous branches and that kind of defeats the purpose of feature/fix-branches
  - braches with only one commit in them? isn't better just rebasing?
* The refactoring of `Data.TSTP` was a great idea! I kind of went "Fork,Tweek, and Forget" on it, I'm glad you took the time to do it

For what I have been able to see, the changes look good, but some git-surgery on the history would be nice, Once we reach some kind of common ground on that issue I can do the changes (if that is ok) to the history and merge.

**Comment by asr** [comment]
> but some git-surgery on the history would be nice

@agomezl, generally speaking, I like the small commits and you can *squash* all the PR in only one commit.

In addition, since you didn't answer us in a couple of months, we didn't know which work-flow to use.

**Comment by agomezl** [comment]
So, in the spirit of not delaying this even longer, I just rebased this changes in top of `master`, the discussion about the workflow and how we want to do thinks can be delayed for later I guess. 

Again, I'm really sorry for taking **so long** to realize this was a thing, it wasn't a lack of interest but stupidity what led to this.

**Comment by asr** [comment]
Thanks for merging.

**Pull request merged**
